<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

In Lab 4.1.1 we were able to predict house price via a predictor variable from first principles. Here we the see how the same can be done using scikit-learn.

For comparison purposes, we will continue with the same predictor `sq__ft` in our dataset as last time.

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [2]:
%pip install seaborn

     ---------------------------------------- 0.0/165.9 kB ? eta -:--:--
     ---------------- ---------------------- 71.7/165.9 kB 2.0 MB/s eta 0:00:01
     -------------------------------------- 165.9/165.9 kB 2.5 MB/s eta 0:00:00
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ------------------- -------------------- 143.4/294.9 kB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 294.9/294.9 kB 3.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.2/8.0 MB 6.6 MB/s eta 0:00:02
   -- ------------------------------------- 0.4/8.0 MB 5.4 MB/s eta 0:00:02
   --- ------------------------------------ 0.6/8.0 MB 4.8 MB/s eta 0:00:02
   ---- ----------------------------------- 0.8/8.0 MB 4.8 MB/s eta 0:00:02
   ----- ---------------------------------- 1.1/8.0 MB 5.1 MB/s eta 0:00:02
   ------- -------------------------------- 1.4/8.0 MB 5.3 MB/s eta 0:00:02
   --------

In [4]:
%pip install scipy

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.8 kB 320.0 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 537.5 kB/s eta 0:00:00
   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   ---------------------------------------- 0.2/44.8 MB 4.1 MB/s eta 0:00:11
   ---------------------------------------- 0.5/44.8 MB 5.1 MB/s eta 0:00:09
    --------------------------------------- 0.7/44.8 MB 6.0 MB/s eta 0:00:08
    --------------------------------------- 1.1/44.8 MB 5.7 MB/s eta 0:00:08
   - -------------------------------------- 1.5/44.8 MB 7.0 MB/s eta 0:00:07
   - -------------------------------------- 1.9/44.8 MB 7.1 MB/s eta 0:00:07
   -- ------------------------------------- 2.3/44.8 MB 7.2 MB/s eta 0:00:06
   -- ------------------------------------- 2.7/44.8 MB 7.5 MB/s eta 0:00:06
   -- ------------------------------------- 3.0/44.8 MB 7.4 MB/s eta 0:00:06
   --

In [5]:
import pandas as pd
import numpy as np
import math
import seaborn as sns
import pandas as pd

from scipy import stats
from matplotlib import pyplot as plt

sns.set_context("poster")
sns.set(rc={'figure.figsize': (10, 6)})
sns.set_style("whitegrid")

%matplotlib inline

### 1. Read in the data

In [15]:
# Read CSV
house_csv = "Sacramento_transactions.csv"
df = pd.read_csv(house_csv)

### 2. Predict Price

We are going to predict the target variable `price` from `sq__ft` using sklearn's linear_model.

Read up on the following methods and attributes here: [sklearn.linear_model.LinearRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)

- coef_
- intercept_
- fit()
- predict()
- score()

In [9]:
%pip install scikit-learn

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.1/11.0 MB 2.8 MB/s eta 0:00:04
   - -------------------------------------- 0.4/11.0 MB 3.8 MB/s eta 0:00:03
   -- ------------------------------------- 0.6/11.0 MB 4.6 MB/s eta 0:00:03
   --- ------------------------------------ 0.9/11.0 MB 5.2 MB/s eta 0:00:02
   ---- ----------------------------------- 1.1/11.0 MB 5.1 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.0 MB 5.0 MB/s eta 0:00:02
   ----- ---------------------------------- 1.5/11.0 MB 4.8 MB/s eta 0:00:02
   ------ --------------------------------- 1.9/11.0 MB 5.1 MB/s eta 0:00:02
   -------- ------------------------------- 2.3/11.0 MB 5.6 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.0 MB 5.7 MB/s eta 0:00:02
   ---------- ----------------------------- 3.0/11.0 MB 5.9 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/11.0 MB 6.2 MB/s eta 0:00:02
   ---

In [10]:
# import the LinearRegression class from the sklearn.linear_model module
from sklearn.linear_model import LinearRegression

#### 2.1 Create an instance of LinearRegression.

In [11]:
# ANSWER
linreg = LinearRegression()

#### 2.2 Fit predictor and target variables using linear regression

In [16]:
X = df['sq__ft'].values.reshape(-1,1)
y = df['price']

In [17]:
# ANSWER
linreg.fit(X, y)

LinearRegression()

#### 2.3. Using attributes of the LinearRegression() class find coefficient and intercept.

In [18]:
# ANSWER

print(linreg.coef_, linreg.intercept_)

[54.15863969] 162930.16140699777


#### 2.4 Find R^2 Score

Find $R^2$ Using the ```score``` method of LinearRegression.

In [19]:
# ANSWER
linreg.score(X, y)

0.11148717682951437

### 3. Splitting Data


Splitting the data into training and test sets is important in supervised learning.

- We ensure that the test set remains untouched during the model training process. This isolation prevents any information leakage about the test set into the training process.

- It allows us to evaluate the performance of our machine learning model on unseen data.


In [20]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Use the `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [21]:
# ANSWER
## Create training and testing subsets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

#### 3.2 Check Shape, Sample of Test Train Data

In [23]:
# ANSWER
## Training
print('X_train is a %s' % type(X_train))
print('X_train has %d rows', X_train.shape[0])
print('')
print('Sample of X_train%s' % ('_'*50))
print(X_train[:10])

print('')
print('y_train is a %s' % type(y_train))
print('y_train has %d rows', y_train.shape)
print('')
print('Sample of y_train%s' % ('_'*50))
print(y_train[:10])

X_train is a <class 'numpy.ndarray'>
X_train has %d rows 788

Sample of X_train__________________________________________________
[[   0]
 [2577]
 [ 722]
 [   0]
 [ 795]
 [   0]
 [1371]
 [   0]
 [1670]
 [1939]]

y_train is a <class 'pandas.core.series.Series'>
y_train has %d rows (788,)

Sample of y_train__________________________________________________
789    313000
818    367463
193    145000
753    267750
377    126960
861    622500
955    208250
689    195000
910    157296
529    423000
Name: price, dtype: int64


In [24]:
#Test
print('X_train is a %s' % type(X_test))
print('X_train has %d rows', X_test.shape)
print('')
print('Sample of X_train%s' % ('_'*50))
print(X_test[:10])

print('')
print('y_train is a %s' % type(y_test))
print('y_train has %d rows', y_test.shape)
print('')
print('Sample of y_train%s' % ('_'*50))
print(y_test[:10])

X_train is a <class 'numpy.ndarray'>
X_train has %d rows (197, 1)

Sample of X_train__________________________________________________
[[1744]
 [1204]
 [1326]
 [   0]
 [1353]
 [   0]
 [2607]
 [1465]
 [2160]
 [1595]]

y_train is a <class 'pandas.core.series.Series'>
y_train has %d rows (197,)

Sample of y_train__________________________________________________
527    416767
930    174250
94     250134
589      4897
417    192000
585      4897
305    402000
239    225000
769    290000
295    339000
Name: price, dtype: int64


#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [25]:
# ANSWER
linreg = LinearRegression()
linreg.fit(X_train, y_train)

print(linreg.coef_, linreg.intercept_)

[54.52848679] 165161.4403527058


In [26]:
# ANSWER
linreg.score(X_test, y_test)

0.09347855366421687

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using the linear regression model.**

In [29]:
# ANSWER
linreg.intercept_, linreg.coef_

(np.float64(165161.4403527058), array([54.52848679]))

In [30]:
beta0 = linreg.intercept_
beta1 = linreg.coef_
x = 1204

Ypred = beta1 * x + beta0
print('Predicted house price: ', Ypred[0])

Predicted house price:  230813.73845315297


In [31]:
x = [[1204]]
Ypred = linreg.predict(x)
print('Predicted house price: ', Ypred[0])

Predicted house price:  230813.73845315297


#### Find the error

In [32]:
# Predict price from X_test
y_preds = linreg.predict(X_test)

y_preds[:10]

array([260259.12132212, 230813.73845315, 237466.21384207, 165161.44035271,
       238938.48298552, 165161.44035271, 307317.20542568, 245045.67350649,
       282942.97182859, 252134.37678976])

In [38]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [39]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, y_preds, squared=True)

np.float64(19855015988.78231)

### Conclusion
We have seen that through scikit-learn, minimal code is needed to implement and evaluate a linear regression model.



---



---



> > > > > > > > > © 2024 Institute of Data


---



---



